name: 🐛 Bug Report
description: Report a reproducible issue with SparkDQ.
labels: [bug]
title: "[BUG] <short description>"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! 🐞  
        Please help us fix the issue by filling out the following details as completely as possible.

  - type: input
    id: environment
    attributes:
      label: 📦 Environment
      description: Please specify your environment details.
      placeholder: "e.g. Python 3.10, PySpark 3.5.0, SparkDQ v0.1.0"
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: 📝 Bug Description
      description: Please describe the issue clearly and concisely.
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔁 Steps to Reproduce
      description: |
        Provide a minimal, reproducible example of the issue.  
        Include code snippets, configuration examples, or sample data if possible.
      placeholder: |
        1. Create a Spark DataFrame with ...
        2. Configure the following check ...
        3. Run validation ...
        4. See error ...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: ✅ Expected Behavior
      description: What should have happened instead?
      placeholder: "The check should pass if ..."

  - type: textarea
    id: logs
    attributes:
      label: 📋 Relevant Logs / Error Messages
      description: Please paste any relevant stack traces, logs, or error outputs.
      render: shell

  - type: textarea
    id: additional_context
    attributes:
      label: 💬 Additional Context
      description: Add any other context about the problem here (e.g. screenshots, related issues).
