name: Test Stage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: "🔍 Code Linting"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:0.6-python3.11-bookworm-slim
    
    steps:
      - uses: actions/checkout@v4

      - name: Install lint dependencies
        run: uv sync --group lint --frozen

      - name: Check code style with Ruff
        run: uv run ruff check .

      - name: Check code formatting with Ruff
        run: uv run ruff format --check .

      - name: Check type hints with mypy
        run: uv run mypy .

  tests:
    name: "🔍 Run Tests"
    needs: lint

    runs-on: ubuntu-latest
    container:
      image: jupyter/pyspark-notebook
      options: --user root

    steps:
      - name: Install git (needed for checkout)
        run: |
          apt-get update && apt-get install -y git

      - uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Install test dependencies
        run: uv sync --group test --frozen

      - name: Run unit tests
        run: uv run pytest --cov=sparkdq -v --cov-report=term --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: sparkdq-community/sparkdq
